
- name: Install epel-release
  package:
    name: epel-release
    state: latest

- name: Update all packages
  package:
    name: "*"
    state: latest

- name: Rebooting post update
  reboot:
    post_reboot_delay: 60
    reboot_timeout: 500
    connect_timeout: 300 
    test_command: uptime

- name: Disable postgresql module repo
  shell: dnf -qy module disable postgresql

- name: Install the postgres repo
  package:
    name: "{{postgres_repo}}"
    state: present
    disable_gpg_check: yes

- name: Install postgresql server
  package:
    name: "{{postgres_server}}"
    #name: postgresql14-server
    state: latest
    disable_gpg_check: yes

- name: Install postgresql contrib packages
  package:
    name: "{{posgres_contrib}}"       
    #name: postgresql14-contrib
    state: latest

- name: Install python3-psycopg2
  package:
    name: python3-psycopg2
    state: latest

- name: Install ansible
  package:
    name: "{{ansible}}"
    state: latest

- name: create user seeker
  user:
    name: "{{app_admin_account}}"
    state: present

- name: Set ACLs for db account
  acl:
    path: "{{seeker_path}}"
    #entity: postgres
    entity: "{{postgres_default}}"
    permissions: rx
    state: present
    etype: user

- name: Install ansible libvrt module
  #shell: ansible-galaxy collection install community.libvirt
  shell: "{{libvirt}}"
  become_user: "{{app_admin_account}}"
  become: True

- name: Reboot post install of postgres
  reboot:
    post_reboot_delay: 60
    reboot_timeout: 500
    connect_timeout: 300
    test_command: uptime
